### ISSUE TITLE
Why create this new layer and not contribute to the Airflow TaskFlow API

### ISSUE THREAD

**Issue by raphaelauv** [astro-projects/astro#227]
Hello, I see this project as a simplification layer on the Apache Airflow native DAG API to author pipelines.

Of course every simplification layer come with advantages and disadvantages -> my main problem is that when I read the example DAG of the README, all the context is hidden , I do not know what code is run and on what database ( where normally the operators explicit what code and connection it use, it's verbose but very clear).

But there is already a simplification layer on Apache airflow to author pipelines the TaskFlow API

Why not contribute to TaskFlow API  than create this new layer ?

**Comment by tatiana** [comment]
Hi @raphaelauv, thank you very much for reaching out!

This project is built on top of Apache Airflow to provide an abstraction to complement it. It aims to promote the TaskFlow API adoption, and not to compete with it.

I agree that this package abstracts several concepts, "hiding" the context and creating intermediate temporary tables for the user. That can make many traditional Airflow users uncomfortable. On the other hand, the simplicity may attract new users - and that's why we see this as an alternative way of authoring DAGs instead of a replacement to the traditional path.

One of the goals of this project is to try out different approaches, iterate fast, and potentially fail/succeed quicker. The Airflow release cycle is slower.

Another goal for this project was to offer a generic connector between databases and files, to simplify ELT. A consequence is that this project depends on several specific Airflow providers (Postgres, Snowflake, Google, and more to come). This path seems to be incompatible with Apache Airflow's core - in the sense that providers are being extracted from the core project.

**Comment by tatiana** [comment]
Our milestones will become our Roadmap and we will be working towards adding more details/issues to them soon, @raphaelauv 
Have you tried the package? Are there any particular features that you'd be interested in?

**Comment by raphaelauv** [comment]
Okay , no I haven't try, I still don't understand the example of the README.

You could explain what is happening ( and also give all the hidden configuration made so it can work ) and also compare to the equivalent normal Airflow DAG.
